### ISSUE TITLE
Mini sachen die mir aufgefallen sind

### ISSUE THREAD

**Issue by nmehlei** [progko-2014/zusammenfassung#1]
Keine Ahnung ob hilfreich und/oder erwünscht, aber kleinere sachen die mir beim anschauen aufgefallen sind: :)

Seite 48:
- Semikolon in mittiger Zeile fehlt

Seite 49:
- "class" müsste kleingeschrieben sein
- Mehrere Semikolons fehlen

Seite 79:
- Typo? Müsste wohl eher "reine Textersetzung" statt "keine Textersetzung" heissen?

**Comment by progko-2014** [comment]
Nicht alle Fehler auffindbar, da wir gestern wieder viel verändert haben.

Tipp: Einfach Pull Request stellen oder einen der Autoren persönlich Fragen für Zugangsdaten und Fehler SELBER ändern :)
